api/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

# for API
from rest_framework.urlpatterns import format_suffix_patterns
from api import views
from django.conf.urls import include

UUID_REGEX_PATTERN = '([a-fA-F0-9]{32}|[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12})'

urlpatterns = patterns('',
    url(r'^addresses/$', views.AddressList.as_view()),
    url(r'^addresses/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.AddressDetail.as_view()),
    
    url(r'^addresses/(?P<address_id>' + UUID_REGEX_PATTERN + '+)/locations/$', views.LocationList.as_view()),
    url(r'^locations/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.LocationDetail.as_view()),
    url(r'^locations/$', views.LocationList.as_view()),
    
    url(r'^parcels/$', views.ParcelList.as_view()),
    url(r'^parcels/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.ParcelDetail.as_view()),

    url(r'^shipments/$', views.ShipmentList.as_view()),
    url(r'^shipments/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.ShipmentDetail.as_view()),
    
    url(r'^shipments/(?P<shipment_id>' + UUID_REGEX_PATTERN + '+)/rates(?:/(?P<currency_iso>([A-Za-z]{3})))?/$', views.RateList.as_view()),
    url(r'^rates/$', views.RateList.as_view()),
    url(r'^rates/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.RateDetail.as_view()),
    
    url(r'^transactions/$', views.TransactionList.as_view()),
    url(r'^transactions/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.TransactionDetail.as_view()),
    
    url(r'^transactions/(?P<transaction_id>' + UUID_REGEX_PATTERN + '+)/tracking/$', views.TrackingList.as_view()),
    url(r'^tracking/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.TrackingDetail.as_view()),
    url(r'^tracking/$', views.TrackingList.as_view()),
)

urlpatterns = format_suffix_patterns(urlpatterns)

urlpatterns += patterns('',
    url(r'^auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
)

shippo/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import RedirectView
from cms.sitemap import *
from cms import views
from django.views.generic import TemplateView

admin.autodiscover()

# a dictionary of sitemaps
sitemaps = {
    'design_pages': DesignPagesSitemap,
    'carrier_pages': CarrierContentSitemap,
    'logistics_pages': SEOPagesSitemap,
    'blog_posts': BlogPostsSitemap,
}

handler404 = 'cms.views.display404Page'
handler500 = 'cms.views.display500Page'

urlpatterns = patterns('',
    url(r'^admin/?', include(admin.site.urls)),
    url(r'^shopify/', include('shopify_app.urls', namespace="shopify_app")),
    url(r'^etsy/', include('etsy_app.urls', namespace="etsy_app")),
    url(r'^', include('user.urls', namespace="user")),
    url(r'^', include('cms.urls', namespace="cms")),
    url(r'^', include('websearch.urls', namespace="websearch")),
    #url(r'^v1/', include('api.urls')),
    url(r'^docs/', include('docs.urls', namespace="docs")),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
)

# General redirect to seopage for all others
urlpatterns += patterns('',
    url(r'^(?P<slug>[a-zA-Z0-9_.-]+)/$', views.displaySEOPage, name='seopage'),
)

#General redirect to docs from root
#urlpatterns += patterns('',
    #url(r'^$', lambda x: redirect('https://goshippo.com')),
#)

user/urls.py
from django.conf.urls import patterns, url
from user import views

urlpatterns = patterns('',
	url(r'^login/$', views.loginUser, name='userlogin'),
    url(r'^register/$', views.registerUser, name='userregistration'),
    #the following activation url is hardcoded in the Mandrill template
    url(r'^activate/(?P<email>[\w|\W]+)/(?P<activation_code>[a-zA-Z0-9_.-]+)/$', views.activateUser, name='useractivation'),
	url(r'^user/logout/$', views.logoutUser, name='userlogout'),
	url(r'^user/dashboard/$', views.UserDashboard, name='userdashboard'),
    url(r'^user/carriers/$', views.CarrierOverview, {'success': False}, name='usercarriers'),
    url(r'^user/carriers/success/$', views.CarrierOverview, {'success': True}, name='usercarrierssuccess'),
    url(r'^user/carriers/success-endicia/$', views.CarrierOverview, {'endicia': True}, name='usercarrierssuccessendicia'),
    url(r'^user/carriers/fedex/$', views.CarrierOverviewFedEx, name='usercarriersfedex'),
    url(r'^user/carriers/ups/$', views.CarrierOverviewUPS, name='usercarriersups'),
    url(r'^user/carriers/usps/$', views.CarrierOverviewUSPS, name='usercarriersusps'),
    url(r'^user/carriers/usps/endicia-registration/$', views.CarrierOverviewUSPSEndiciaRegistration, name='usercarriersuspsendiciaregistration'),
    url(r'^user/carriers/parcel2go/$', views.CarrierOverviewParcel2Go, name='usercarriersparcel2go'),
    url(r'^user/carriers/royalmail/$', views.CarrierOverviewRoyalMail, name='usercarriersroyalmail'),
    url(r'^user/carriers/deutschepost/$', views.CarrierOverviewDeutschePost, name='usercarriersdeutschepost'),
    url(r'^user/carriers/deutschepostdhl/$', views.CarrierOverviewDeutschePostDHL, name='usercarriersdeutschepostdhl'),
    url(r'^user/profile/$', views.UserProfile, name='userprofile'),
    url(r'^user/apikeys/$', views.UserAPIKeys, name='userapikeys'),
    url(r'^user/billing/$', views.UserBilling, name='userbilling'),
    url(r'^user/orders/$', views.UserOrders, name='userorders'),
    url(r'^user/orders/not-found/$', views.UserOrders, {'order_not_found': True}, name='userordersordernotfound'),
    url(r'^user/orders/(?P<order_id>[a-zA-Z0-9_.-]+)/$', views.UserOrderInfo, name='userorderinfo'),
    url(r'^user/orders/(?P<order_id>[a-zA-Z0-9_.-]+)/rates/$', views.UserOrderRates, name='userorderrates'),
    url(r'^user/orders/(?P<order_id>[a-zA-Z0-9_.-]+)/(?P<fulfillment_id>[a-zA-Z0-9_.-]+)/label/$', views.UserOrderLabel, name='userorderlabelbase'),
    url(r'^user/orders/(?P<order_id>[a-zA-Z0-9_.-]+)/(?P<fulfillment_id>[a-zA-Z0-9_.-]+)/label/(?P<rate_id>[a-zA-Z0-9_.-]+)/$', views.UserOrderLabel, name='userorderlabel'),
)

user/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from models import *
from api.models import *
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from rest_framework.authtoken.models import Token
from django.conf import settings
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import uuid, sys, stripe, requests, datetime
from shopify_app.models import ShipmentTransaction
from shopify_app.helpers.import_orders import import_orders as import_shopify_orders
from etsy_app.helpers.import_orders import import_orders as import_etsy_orders
from cms.helpers.mandrill.base import MandrillMailService
from rq import Queue
from worker import conn
from websearch.shippo_api.shippo_api import ShippoAPI
from django.core.mail import send_mail

def loginFunction(request):
    error = True
    success = False
    if request.method == 'POST':
        try:
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    success = True
                else:
                    error = 'Your account is currently disabled. Have you already confirmed your e-mail?'
            else:
                error = 'Your e-mail or password is incorrect. Please try again!'
        except KeyError:
            error = 'There was a problem processing your data. Please try again or contact info@goshippo.com for more information. Sorry for the trouble!'
    return success, error

def registerUser(request):
    error = False
    success = False
    new_user = False
    if request.method == 'POST':
        email = request.POST['email']
        #check if username (=email) already exists
        existing_user = User.objects.filter(username=email)
        if existing_user:
            error = 'This e-mail address is already registered. Please use a different one or contact info@goshippo.com for help.'
        else:
            password = request.POST['password']
            first_name = request.POST['first_name']
            last_name = request.POST['last_name']
            password = request.POST['password']
            #create User object
            new_user = User.objects.create_user(email, email, password)
            new_user.first_name = first_name
            new_user.last_name = last_name
            new_user.save()
            #we need to also create an APIUser (APIAddress and APIBilling will be handled by signals.py)
            new_apiuser = APIUser(user=new_user)
            #save a random activation code for email confirmation
            new_apiuser.shippo_activation_code = str(uuid.uuid4())
            new_apiuser.mixpanel_user_id = email
            new_apiuser.save()
            new_user.apiuser = new_apiuser
            #set user to false due to email confirmation
            new_user.is_active = False
            new_user.save()
            #queue activation mail
            q = Queue('low', connection=conn)
            q.enqueue_call(func=sendActivationMail, args=(new_apiuser,), result_ttl=0)
            #send Hipchat notif
            q = Queue('low', connection=conn)
            q.enqueue_call(func=sendHipchatNotif, args=(new_user,), result_ttl=0)
            #return success message
            success = 'Successfully registered! Please check your e-mail inbox to activate your account.'
    # we also return the (registered) user object to track regsitration on Mixpanel via JS
    context = {'error': error, 'success': success, 'new_user': new_user}
    return render(request, 'registration/registration.html', context)

def sendActivationMail(apiuser):
    #we need a separate function for that since RQ apparently can't handle methods
    mandrill_mail = MandrillMailService()
    return mandrill_mail.ActivationMail(apiuser)

def sendHipchatNotif(user):
    #we need to write a helper for that
    base_url = 'https://api.hipchat.com/v1/rooms/message'
    params = {
        'auth_token': '04ad28d4e7518895b480aad3cc15e8',
        'room_id': '249701',
        'from': 'Shippo Admin',
        'message': 'New API registration: ' + user.first_name + ' ' + user.last_name + ' (' + user.email + ')',
        'color': 'green',
        'notify': '1'
    }
    r = requests.get(base_url, params=params)
    return True

def activateUser(request, email, activation_code):
    error = False
    try:
        #get user for email who is not active
        email = email.replace('%40', '@')
        user = User.objects.get(email=email, is_active=False)
        #get apiuser for activation code that matches the user
        apiuser = APIUser.objects.get(shippo_activation_code=activation_code, user=user)
        if user and apiuser:
            #activate user
            user.is_active = True
            user.save()
            #queue welcome mail
            q = Queue('low', connection=conn)
            q.enqueue_call(func=sendWelcomeMail, args=(apiuser,), result_ttl=0)
            #forward user to login page
            context = {'success': 'You have successfully activated your account. Log in now to start shipping in minutes!'}
            return render(request, 'registration/login.html', context)
    except:
        error = 'We did not find a user for this URL that needs to be activated. Please try again or contact info@goshippo.com for help.'
    context = {'error': error}
    return render(request, 'registration/activation.html', context)

def sendWelcomeMail(apiuser):
    #we need a separate function for that since RQ apparently can't handle methods
    mandrill_mail = MandrillMailService()
    return mandrill_mail.WelcomeMail(apiuser)

def loginUser(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('user:userdashboard'))
    error = False
    if request.method == 'POST':
        success, error = loginFunction(request)
        if success:
            return HttpResponseRedirect(reverse('user:userdashboard'))
    context = {'error': error}
    return render(request, 'registration/login.html', context)

def logoutUser(request):
    logout(request)
    return HttpResponseRedirect(reverse('cms:homepage'))

@login_required
def CarrierOverview(request, success=False, endicia=False):
    apiuser = APIUser.objects.get(user=request.user)
    context = {'modal': False, 'success': success, 'endicia_success': endicia}
    return render(request, 'user/carriers.html', context)

@login_required
def CarrierOverviewFedEx(request):
    current_user = request.user
    apiuser = APIUser.objects.get(user=current_user)
    error = False
    if request.method == 'POST':
        try:
            apiuser.fedex_account = request.POST['fedex_account']
            apiuser.fedex_meter = request.POST['fedex_meter']
            if request.POST['fedex_production'] == 'True': apiuser.fedex_production = True
            elif request.POST['fedex_production'] == 'False': apiuser.fedex_production = False
            apiuser.save()
            return HttpResponseRedirect(reverse('user:usercarrierssuccess'))
        except:
            error = 'There was a problem saving your data.'
    context = {'modal': True, 'error': error}
    return render(request, 'user/carriers/fedex.html', context)

@login_required
def CarrierOverviewUPS(request):
    current_user = request.user
    apiuser = APIUser.objects.get(user=current_user)
    error = False
    if request.method == 'POST':
        try:
            apiuser.ups_account = request.POST['ups_account']
            apiuser.ups_user_id = request.POST['ups_user_id']
            apiuser.ups_password = request.POST['ups_password']
            if request.POST['ups_production'] == 'True': apiuser.ups_production = True
            elif request.POST['ups_production'] == 'False': apiuser.ups_production = False
            apiuser.save()
            return HttpResponseRedirect(reverse('user:usercarrierssuccess'))
        except:
            error = 'There was a problem saving your data.'
    context = {'modal': True, 'error': error}
    return render(request, 'user/carriers/ups.html', context)

@login_required
def CarrierOverviewUSPS(request):
    current_user = request.user
    apiuser = APIUser.objects.get(user=current_user)
    error = False
    if request.method == 'POST':
        try:
            if not apiuser.endicia_temporary_account:
                apiuser.endicia_account_id = request.POST['endicia_account_id']
                #only save passphrase if no temporary account (i.e. just created via Endicia API)
                apiuser.endicia_passphrase = request.POST['endicia_passphrase']
                apiuser.endicia_refill_amount = request.POST['endicia_refill_amount']
                if request.POST['endicia_production'] == 'True': apiuser.endicia_production = True
                elif request.POST['endicia_production'] == 'False': apiuser.endicia_production = False
                apiuser.save()
            if apiuser.endicia_temporary_account:
                #we need to reset the passphrase after user has been created through the API
                from adapter.endicia.config import EndiciaConfig
                from adapter.endicia.user_service import EndiciaUserService
                config = EndiciaConfig(current_user)
                adapter = EndiciaUserService(config)
                new_passphrase = str(uuid.uuid4())
                response = adapter.change_passphrase(new_passphrase)
                if response == True:
                    #passphrase successfully changed
                    apiuser.endicia_account_id = request.POST['endicia_account_id']
                    apiuser.endicia_passphrase = new_passphrase

user/templates/user/carriers/deutschepost.html
{% extends "user/carriers.html" %}

{% block modaltitle %}Deutsche Post Account Settings{% endblock %}

{% block modalbody %}

  {% if error_message %}
    <div class="alert alert-error alert-dismissable">
    	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>{{ error_message }}</strong>
    </div>
  {% endif %}

    <div class="padding-v-xs text-center">
      <h3>Enter your Deutsche Post Settings</h3>
      <!--<p><small>In order to purchase labels, you need to activate Deutsche Post production mode.</small></p>-->
      <form action="{% url 'user:usercarriersdeutschepost' %}" method="post">
        {% csrf_token %}
        <p><small>To purchase Deutsche Post rates, you need to save your Deutsche Post Portokasse username and password.</small></p>
        <p><input autocomplete="off" type="text" name="portokasse_mail" class="form-control" id="portokasse_mail" placeholder="Portokasse Username" value="{{ apiuser.portokasse_mail }}"></p>
        <p><input autocomplete="off" type="password" name="portokasse_password" class="form-control" id="portokasse_password" placeholder="Portokasse Password" value="{{ apiuser.portokasse_password }}"></p>
        <p><small>Use Deutsche Post in production?</small></p>
        <div class="row text-left margin-bt-sm">
          <div class="col-xs-6 col-xs-offset-3">
            <div class="toggle-buttons">
              <input id="active" name="deutsche_post_production" value="True" type="radio" {% if apiuser.deutsche_post_production %}checked=""{% endif %}>
              <label for="active" onclick="">Active</label>
              <input id="inactive" name="deutsche_post_production" value="False" type="radio" {% if not apiuser.deutsche_post_production %}checked=""{% endif %}>
              <label for="inactive" onclick="">Only Test</label>
              <a></a><!--empty a needed to overcome transition bug-->
            </div>
          </div>
        </div>
        <p class="margin-t-md"><button type="submit" class="btn btn-primary">Save Changes</button></p>
      </form>
    </div>

{% endblock %}

user/templates/user/carriers/deutschepostdhl.html
{% extends "user/carriers.html" %}

{% block modaltitle %}Deutsche Post DHL Account Settings{% endblock %}

{% block modalbody %}

  {% if error_message %}
    <div class="alert alert-error alert-dismissable">
    	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>{{ error_message }}</strong>
    </div>
  {% endif %}

    <div class="padding-v-xs text-center">
      <h3>Enter your Deutsche Post DHL Settings</h3>
      {% if wewanttoactivateitinthefuture %}
        <p><small>DHL offers both consumer and business rates. Please choose, which ones you want to activate for obtaining labels and
          set your account data if needed.</small></p>
      {% endif %}
      <form action="{% url 'user:usercarriersdeutschepostdhl' %}" method="post">
        {% csrf_token %}
        <h4 class="border-bottom text-primary">DHL Business rates</h4>
        <p><small>In order to get rates and obtain labels, you need to set your DHL account and intraship details.</small></p>
        <p><small>For test mode, you may use account number <em>50000000007201</em>, intraship user <em>geschaeftskunden_api</em> and intraship password <em>Dhl_ep_test1</em>.</small></p>
        <p><input autocomplete="off" type="text" name="dhl_account_number" class="form-control" id="dhl_account_number" placeholder="DHL Account Number" value="{{ apiuser.dhl_account_number }}"></p>
        <p><input autocomplete="off" type="text" name="dhl_intraship_username" class="form-control" id="dhl_intraship_username" placeholder="DHL Intraship Username" value="{{ apiuser.dhl_intraship_username }}"></p>
        <p><input autocomplete="off" type="password" name="dhl_intraship_password" class="form-control" id="dhl_intraship_password" placeholder="DHL Intraship Password" value="{{ apiuser.dhl_intraship_password }}"></p>
        <p><small>Use Deutsche Post DHL (Business) in production?</small></p>
        <div class="row text-left margin-bt-sm">
          <div class="col-xs-6 col-xs-offset-3">
            <div class="toggle-buttons">
              <input id="business_active" name="dhl_production" value="True" type="radio" {% if apiuser.dhl_production %}checked=""{% endif %}>
              <label for="business_active" onclick="">Active</label>
              <input id="business_inactive" name="dhl_production" value="False" type="radio" {% if not apiuser.dhl_production %}checked=""{% endif %}>
              <label for="business_inactive" onclick="">Only Test</label>
              <a></a><!--empty a needed to overcome transition bug-->
            </div>
          </div>
        </div>
        {% if wewanttoactivateitinthefuture %}
          <h4 class="border-bottom text-primary">DHL Consumer rates</h4>
          <p><small>To purchase consumer rates, you need to save your PostPay username and password.</small></p>
          <p><input autocomplete="off" type="text" name="postpay_mail" class="form-control" id="postpay_mail" placeholder="DHL PostPay Username" value="{{ apiuser.postpay_mail }}"></p>
          <p><input autocomplete="off" type="password" name="postpay_password" class="form-control" id="postpay_password" placeholder="DHL PostPay Password" value="{{ apiuser.postpay_password }}"></p>
          <p><small>Use Deutsche Post DHL (Consumer) in production?</small></p>
          <div class="row text-left margin-bt-sm">
            <div class="col-xs-6 col-xs-offset-3">
              <div class="toggle-buttons">
                <input id="consumer_active" name="dp_dhl_production" value="True" type="radio" {% if apiuser.dp_dhl_production %}checked=""{% endif %}>
                <label for="consumer_active" onclick="">Active</label>
                <input id="consumer_inactive" name="dp_dhl_production" value="False" type="radio" {% if not apiuser.dp_dhl_production %}checked=""{% endif %}>
                <label for="consumer_inactive" onclick="">Only Test</label>
                <a></a><!--empty a needed to overcome transition bug-->
              </div>
            </div>
          </div>
        {% endif %}
        <p class="margin-t-md"><button type="submit" class="btn btn-primary">Save Changes</button></p>
      </form>
    </div>

{% endblock %}

user/templates/user/carriers/fedex.html
{% extends "user/carriers.html" %}

{% block modaltitle %}FedEx Account Settings{% endblock %}

{% block modalbody %}

  {% if error_message %}
    <div class="alert alert-error alert-dismissable">
    	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>{{ error_message }}</strong>
    </div>
  {% endif %}

    <div class="padding-v-xs text-center">
      <h3>Enter your FedEx account</h3>
      <p><small>In order to get rates and purchase labels, you need to enter your <strong>FedEx account details</strong>. Please note that you need to use different credentials for the FedEx Test and Production Servers.</small></p>
      <form action="{% url 'user:usercarriersfedex' %}" method="post">
        {% csrf_token %}
        <p><input autocomplete="off" type="number" name="fedex_account" class="form-control" id="fedex_account" placeholder="FedEx Account Number" value="{{ apiuser.fedex_account }}"></p>
        <p><input autocomplete="off" type="number" name="fedex_meter" class="form-control" id="fedex_meter" placeholder="FedEx Meter Number" value="{{ apiuser.fedex_meter }}"></p>
        <p><small>Use your FedEx account in production?</small></p>
        <div class="row text-left margin-bt-sm">
          <div class="col-xs-6 col-xs-offset-3">
            <div class="toggle-buttons">
              <input id="active" name="fedex_production" value="True" type="radio" {% if apiuser.fedex_production %}checked=""{% endif %}>
              <label for="active" onclick="">Active</label>
              <input id="inactive" name="fedex_production" value="False" type="radio" {% if not apiuser.fedex_production %}checked=""{% endif %}>
              <label for="inactive" onclick="">Only Test</label>
              <a></a><!--empty a needed to overcome transition bug-->
            </div>
          </div>
        </div>
        <p class="margin-t-md"><button type="submit" class="btn btn-primary">Save Changes</button></p>
      </form>
    </div>
    <hr>
    <div class="text-center padding-bt-sm margin-b-xs">
      <h3>Need a new account?</h3>
      <p>Create one now, it's free! We've covered the detailed account creation for you in a blog post.</p>
      <a class="btn btn-blue" href="/blog/find-sign-up-right-fedex-account/">Create Free FedEx Account</a>
    </div>

{% endblock %}

user/templates/user/carriers/parcel2go.html
{% extends "user/carriers.html" %}

{% block modaltitle %}Parcel2Go Account Settings{% endblock %}

{% block modalbody %}

  {% if error_message %}
    <div class="alert alert-error alert-dismissable">
    	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>{{ error_message }}</strong>
    </div>
  {% endif %}

    <div class="padding-v-xs text-center">
      <h3>Enter your Parcel2Go API Key</h3>
      <p><small>Parcel2Go is a UK multi-carrier provider, offering discounted labels for various carriers. In order to purchase labels, you need to enter your <strong>Parcel2Go API Key</strong>.</small></p>
      <form action="{% url 'user:usercarriersparcel2go' %}" method="post">
        {% csrf_token %}
        <p><input autocomplete="off" type="text" name="parcel2go_api_key" class="form-control" id="parcel2go_api_key" placeholder="Parcel2Go API Key" value="{{ apiuser.parcel2go_api_key }}"></p>
        <p><small><em>Optional: enter your stored credit card reference. Leave this field blank to use your prepaid account.</em></small></p>
        <p><input autocomplete="off" type="text" name="parcel2go_card_reference" class="form-control" id="parcel2go_card_reference" placeholder="Parcel2Go Stored Card Reference" value="{{ apiuser.parcel2go_card_reference }}"></p>
        <p><small>Use your Parcel2Go account in production?</small></p>
        <div class="row text-left margin-bt-sm">
          <div class="col-xs-6 col-xs-offset-3">
            <div class="toggle-buttons">
              <input id="active" name="parcel2go_production" value="True" type="radio" {% if apiuser.parcel2go_production %}checked=""{% endif %}>
              <label for="active" onclick="">Active</label>
              <input id="inactive" name="parcel2go_production" value="False" type="radio" {% if not apiuser.parcel2go_production %}checked=""{% endif %}>
              <label for="inactive" onclick="">Only Test</label>
              <a></a><!--empty a needed to overcome transition bug-->
            </div>
          </div>
        </div>
        <p class="margin-t-md"><button type="submit" class="btn btn-primary">Save Changes</button></p>
      </form>
    </div>
    <hr>
    <div class="text-center padding-bt-sm margin-b-xs">
      <h3>Need a new account?</h3>
      <p>Create one now, it's free and doesn't take longer than 5 minutes!</p>
      <a class="btn btn-blue" href="http://www.parcel2go.com/">Create Free Parcel2Go Account</a>
    </div>

{% endblock %}

user/templates/user/carriers/royalmail.html
{% extends "user/carriers.html" %}

{% block modaltitle %}Royal Mail Account Settings{% endblock %}

{% block modalbody %}

  {% if error_message %}
    <div class="alert alert-error alert-dismissable">
    	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>{{ error_message }}</strong>
    </div>
  {% endif %}

    <div class="padding-v-xs text-center">
      <h3>Enter your Royal Mail Settings</h3>
      <p><small>In order to get rates and purchase labels, please enter your Royal Mail user account.</small></p>
      <form action="{% url 'user:usercarriersroyalmail' %}" method="post">
        {% csrf_token %}
        <p><input autocomplete="off" type="text" name="royalmail_username" class="form-control" id="royalmail_username" placeholder="Royal Mail Username" value="{{ apiuser.royalmail_username }}"></p>
        <p><input autocomplete="off" type="password" name="royalmail_password" class="form-control" id="royalmail_password" placeholder="Royal Mail Password" value="{{ apiuser.royalmail_password }}"></p>
        <p><small>Use Royal Mail in production?</small></p>
        <div class="row text-left margin-bt-sm">
          <div class="col-xs-6 col-xs-offset-3">
            <div class="toggle-buttons">
              <input id="active" name="royalmail_production" value="True" type="radio" {% if apiuser.royalmail_production %}checked=""{% endif %}>
              <label for="active" onclick="">Active</label>
              <input id="inactive" name="royalmail_production" value="False" type="radio" {% if not apiuser.royalmail_production %}checked=""{% endif %}>
              <label for="inactive" onclick="">Only Test</label>
              <a></a><!--empty a needed to overcome transition bug-->
            </div>
          </div>
        </div>
        <p class="margin-t-md"><button type="submit" class="btn btn-primary">Save Changes</button></p>
      </form>
    </div>

{% endblock %}