api/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

# for API
from rest_framework.urlpatterns import format_suffix_patterns
from api import views
from django.conf.urls import include

UUID_REGEX_PATTERN = '([a-fA-F0-9]{32}|[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12})'

urlpatterns = patterns('',
    url(r'^addresses/$', views.AddressList.as_view()),
    url(r'^addresses/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.AddressDetail.as_view()),
    
    url(r'^addresses/(?P<address_id>' + UUID_REGEX_PATTERN + '+)/locations/$', views.LocationList.as_view()),
    url(r'^locations/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.LocationDetail.as_view()),
    url(r'^locations/$', views.LocationList.as_view()),
    
    url(r'^parcels/$', views.ParcelList.as_view()),
    url(r'^parcels/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.ParcelDetail.as_view()),

    url(r'^shipments/$', views.ShipmentList.as_view()),
    url(r'^shipments/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.ShipmentDetail.as_view()),
    
    url(r'^shipments/(?P<shipment_id>' + UUID_REGEX_PATTERN + '+)/rates(?:/(?P<currency_iso>([A-Za-z]{3})))?/$', views.RateList.as_view()),
    url(r'^rates/$', views.RateList.as_view()),
    url(r'^rates/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.RateDetail.as_view()),
    
    url(r'^transactions/$', views.TransactionList.as_view()),
    url(r'^transactions/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.TransactionDetail.as_view()),
    
    url(r'^transactions/(?P<transaction_id>' + UUID_REGEX_PATTERN + '+)/tracking/$', views.TrackingList.as_view()),
    url(r'^tracking/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.TrackingDetail.as_view()),
    url(r'^tracking/$', views.TrackingList.as_view()),
)

urlpatterns = format_suffix_patterns(urlpatterns)

urlpatterns += patterns('',
    url(r'^auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
)

shippo/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import RedirectView
from cms.sitemap import *
from cms import views
from django.views.generic import TemplateView

admin.autodiscover()

# a dictionary of sitemaps
sitemaps = {
    'design_pages': DesignPagesSitemap,
    'carrier_pages': CarrierContentSitemap,
    'logistics_pages': SEOPagesSitemap,
    'blog_posts': BlogPostsSitemap,
}

handler404 = 'cms.views.display404Page'
handler500 = 'cms.views.display500Page'

urlpatterns = patterns('',
    url(r'^admin/?', include(admin.site.urls)),
    url(r'^shopify/', include('shopify_app.urls', namespace="shopify_app")),
    url(r'^etsy/', include('etsy_app.urls', namespace="etsy_app")),
    url(r'^', include('user.urls', namespace="user")),
    url(r'^', include('cms.urls', namespace="cms")),
    url(r'^', include('websearch.urls', namespace="websearch")),
    #url(r'^v1/', include('api.urls')),
    url(r'^docs/', include('docs.urls', namespace="docs")),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
)

# General redirect to seopage for all others
urlpatterns += patterns('',
    url(r'^(?P<slug>[a-zA-Z0-9_.-]+)/$', views.displaySEOPage, name='seopage'),
)

#General redirect to docs from root
#urlpatterns += patterns('',
    #url(r'^$', lambda x: redirect('https://goshippo.com')),
#)

user/urls.py
from django.conf.urls import patterns, url
from user import views

urlpatterns = patterns('',
	url(r'^login/$', views.loginUser, name='userlogin'),
    url(r'^register/$', views.registerUser, name='userregistration'),
    #the following activation url is hardcoded in the Mandrill template
    url(r'^activate/(?P<email>[\w|\W]+)/(?P<activation_code>[a-zA-Z0-9_.-]+)/$', views.activateUser, name='useractivation'),
	url(r'^user/logout/$', views.logoutUser, name='userlogout'),
	url(r'^user/dashboard/$', views.UserDashboard, name='userdashboard'),
    url(r'^user/carriers/$', views.CarrierOverview, {'success': False}, name='usercarriers'),
    url(r'^user/carriers/success/$', views.CarrierOverview, {'success': True}, name='usercarrierssuccess'),
    url(r'^user/carriers/success-endicia/$', views.CarrierOverview, {'endicia': True}, name='usercarrierssuccessendicia'),
    url(r'^user/carriers/fedex/$', views.CarrierOverviewFedEx, name='usercarriersfedex'),
    url(r'^user/carriers/ups/$', views.CarrierOverviewUPS, name='usercarriersups'),
    url(r'^user/carriers/usps/$', views.CarrierOverviewUSPS, name='usercarriersusps'),
    url(r'^user/carriers/usps/endicia-registration/$', views.CarrierOverviewUSPSEndiciaRegistration, name='usercarriersuspsendiciaregistration'),
    url(r'^user/carriers/parcel2go/$', views.CarrierOverviewParcel2Go, name='usercarriersparcel2go'),
    url(r'^user/carriers/royalmail/$', views.CarrierOverviewRoyalMail, name='usercarriersroyalmail'),
    url(r'^user/carriers/deutschepost/$', views.CarrierOverviewDeutschePost, name='usercarriersdeutschepost'),
    url(r'^user/carriers/deutschepostdhl/$', views.CarrierOverviewDeutschePostDHL, name='usercarriersdeutschepostdhl'),
    url(r'^user/profile/$', views.UserProfile, name='userprofile'),
    url(r'^user/apikeys/$', views.UserAPIKeys, name='userapikeys'),
    url(r'^user/billing/$', views.UserBilling, name='userbilling'),
    url(r'^user/orders/$', views.UserOrders, name='userorders'),
    url(r'^user/orders/not-found/$', views.UserOrders, {'order_not_found': True}, name='userordersordernotfound'),
    url(r'^user/orders/(?P<order_id>[a-zA-Z0-9_.-]+)/$', views.UserOrderInfo, name='userorderinfo'),
    url(r'^user/orders/(?P<order_id>[a-zA-Z0-9_.-]+)/rates/$', views.UserOrderRates, name='userorderrates'),
    url(r'^user/orders/(?P<order_id>[a-zA-Z0-9_.-]+)/(?P<fulfillment_id>[a-zA-Z0-9_.-]+)/label/$', views.UserOrderLabel, name='userorderlabelbase'),
    url(r'^user/orders/(?P<order_id>[a-zA-Z0-9_.-]+)/(?P<fulfillment_id>[a-zA-Z0-9_.-]+)/label/(?P<rate_id>[a-zA-Z0-9_.-]+)/$', views.UserOrderLabel, name='userorderlabel'),
)

user/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from models import *
from api.models import *
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from rest_framework.authtoken.models import Token
from django.conf import settings
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import uuid, sys, stripe, requests, datetime
from shopify_app.models import ShipmentTransaction
from shopify_app.helpers.import_orders import import_orders as import_shopify_orders
from etsy_app.helpers.import_orders import import_orders as import_etsy_orders
from cms.helpers.mandrill.base import MandrillMailService
from rq import Queue
from worker import conn
from websearch.shippo_api.shippo_api import ShippoAPI
from django.core.mail import send_mail

def loginFunction(request):
    error = True
    success = False
    if request.method == 'POST':
        try:
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    success = True
                else:
                    error = 'Your account is currently disabled. Have you already confirmed your e-mail?'
            else:
                error = 'Your e-mail or password is incorrect. Please try again!'
        except KeyError:
            error = 'There was a problem processing your data. Please try again or contact info@goshippo.com for more information. Sorry for the trouble!'
    return success, error

def registerUser(request):
    error = False
    success = False
    new_user = False
    if request.method == 'POST':
        email = request.POST['email']
        #check if username (=email) already exists
        existing_user = User.objects.filter(username=email)
        if existing_user:
            error = 'This e-mail address is already registered. Please use a different one or contact info@goshippo.com for help.'
        else:
            password = request.POST['password']
            first_name = request.POST['first_name']
            last_name = request.POST['last_name']
            password = request.POST['password']
            #create User object
            new_user = User.objects.create_user(email, email, password)
            new_user.first_name = first_name
            new_user.last_name = last_name
            new_user.save()
            #we need to also create an APIUser (APIAddress and APIBilling will be handled by signals.py)
            new_apiuser = APIUser(user=new_user)
            #save a random activation code for email confirmation
            new_apiuser.shippo_activation_code = str(uuid.uuid4())
            new_apiuser.mixpanel_user_id = email
            new_apiuser.save()
            new_user.apiuser = new_apiuser
            #set user to false due to email confirmation
            new_user.is_active = False
            new_user.save()
            #queue activation mail
            q = Queue('low', connection=conn)
            q.enqueue_call(func=sendActivationMail, args=(new_apiuser,), result_ttl=0)
            #send Hipchat notif
            q = Queue('low', connection=conn)
            q.enqueue_call(func=sendHipchatNotif, args=(new_user,), result_ttl=0)
            #return success message
            success = 'Successfully registered! Please check your e-mail inbox to activate your account.'
    # we also return the (registered) user object to track regsitration on Mixpanel via JS
    context = {'error': error, 'success': success, 'new_user': new_user}
    return render(request, 'registration/registration.html', context)

def sendActivationMail(apiuser):
    #we need a separate function for that since RQ apparently can't handle methods
    mandrill_mail = MandrillMailService()
    return mandrill_mail.ActivationMail(apiuser)

def sendHipchatNotif(user):
    #we need to write a helper for that
    base_url = 'https://api.hipchat.com/v1/rooms/message'
    params = {
        'auth_token': '04ad28d4e7518895b480aad3cc15e8',
        'room_id': '249701',
        'from': 'Shippo Admin',
        'message': 'New API registration: ' + user.first_name + ' ' + user.last_name + ' (' + user.email + ')',
        'color': 'green',
        'notify': '1'
    }
    r = requests.get(base_url, params=params)
    return True

def activateUser(request, email, activation_code):
    error = False
    try:
        #get user for email who is not active
        email = email.replace('%40', '@')
        user = User.objects.get(email=email, is_active=False)
        #get apiuser for activation code that matches the user
        apiuser = APIUser.objects.get(shippo_activation_code=activation_code, user=user)
        if user and apiuser:
            #activate user
            user.is_active = True
            user.save()
            #queue welcome mail
            q = Queue('low', connection=conn)
            q.enqueue_call(func=sendWelcomeMail, args=(apiuser,), result_ttl=0)
            #forward user to login page
            context = {'success': 'You have successfully activated your account. Log in now to start shipping in minutes!'}
            return render(request, 'registration/login.html', context)
    except:
        error = 'We did not find a user for this URL that needs to be activated. Please try again or contact info@goshippo.com for help.'
    context = {'error': error}
    return render(request, 'registration/activation.html', context)

def sendWelcomeMail(apiuser):
    #we need a separate function for that since RQ apparently can't handle methods
    mandrill_mail = MandrillMailService()
    return mandrill_mail.WelcomeMail(apiuser)

def loginUser(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('user:userdashboard'))
    error = False
    if request.method == 'POST':
        success, error = loginFunction(request)
        if success:
            return HttpResponseRedirect(reverse('user:userdashboard'))
    context = {'error': error}
    return render(request, 'registration/login.html', context)

def logoutUser(request):
    logout(request)
    return HttpResponseRedirect(reverse('cms:homepage'))

@login_required
def CarrierOverview(request, success=False, endicia=False):
    apiuser = APIUser.objects.get(user=request.user)
    context = {'modal': False, 'success': success, 'endicia_success': endicia}
    return render(request, 'user/carriers.html', context)

@login_required
def CarrierOverviewFedEx(request):
    current_user = request.user
    apiuser = APIUser.objects.get(user=current_user)
    error = False
    if request.method == 'POST':
        try:
            apiuser.fedex_account = request.POST['fedex_account']
            apiuser.fedex_meter = request.POST['fedex_meter']
            if request.POST['fedex_production'] == 'True': apiuser.fedex_production = True
            elif request.POST['fedex_production'] == 'False': apiuser.fedex_production = False
            apiuser.save()
            return HttpResponseRedirect(reverse('user:usercarrierssuccess'))
        except:
            error = 'There was a problem saving your data.'
    context = {'modal': True, 'error': error}
    return render(request, 'user/carriers/fedex.html', context)

@login_required
def CarrierOverviewUPS(request):
    current_user = request.user
    apiuser = APIUser.objects.get(user=current_user)
    error = False
    if request.method == 'POST':
        try:
            apiuser.ups_account = request.POST['ups_account']
            apiuser.ups_user_id = request.POST['ups_user_id']
            apiuser.ups_password = request.POST['ups_password']
            if request.POST['ups_production'] == 'True': apiuser.ups_production = True
            elif request.POST['ups_production'] == 'False': apiuser.ups_production = False
            apiuser.save()
            return HttpResponseRedirect(reverse('user:usercarrierssuccess'))
        except:
            error = 'There was a problem saving your data.'
    context = {'modal': True, 'error': error}
    return render(request, 'user/carriers/ups.html', context)

@login_required
def CarrierOverviewUSPS(request):
    current_user = request.user
    apiuser = APIUser.objects.get(user=current_user)
    error = False
    if request.method == 'POST':
        try:
            if not apiuser.endicia_temporary_account:
                apiuser.endicia_account_id = request.POST['endicia_account_id']
                #only save passphrase if no temporary account (i.e. just created via Endicia API)
                apiuser.endicia_passphrase = request.POST['endicia_passphrase']
                apiuser.endicia_refill_amount = request.POST['endicia_refill_amount']
                if request.POST['endicia_production'] == 'True': apiuser.endicia_production = True
                elif request.POST['endicia_production'] == 'False': apiuser.endicia_production = False
                apiuser.save()
            if apiuser.endicia_temporary_account:
                #we need to reset the passphrase after user has been created through the API
                from adapter.endicia.config import EndiciaConfig
                from adapter.endicia.user_service import EndiciaUserService
                config = EndiciaConfig(current_user)
                adapter = EndiciaUserService(config)
                new_passphrase = str(uuid.uuid4())
                response = adapter.change_passphrase(new_passphrase)
                if response == True:
                    #passphrase successfully changed
                    apiuser.endicia_account_id = request.POST['endicia_account_id']
                    apiuser.endicia_passphrase = new_passphrase

user/templates/user/apikeys.html
{% extends "user/internal.html" %}
{% load staticfiles %}

{% block title %}API Keys - Shippo{% endblock %}

{% block internalmenu %}

<h3 class="text-primary border-bottom">Your Shippo API Keys</h3>
<div class="row margin-bt-md">
  <div class="col-sm-6 col-xs-12">
    <div class="form-group">
      <label for="api_test_key" class="control-label"><strong>Basic Auth Key</strong></label>
      <input disabled type="text" name="user_firstname" class="form-control" id="api_basic_auth" value="{{ user.email }}:[YOUR_PASSWORD]">
      <em><small>Basic Auth requires you to base64-encode the username:password string.</small></em>
    </div>
    <div class="form-group margin-t-md">
      <label for="api_test_key" class="control-label"><strong>Token Auth Key</strong></label>
      <input disabled type="text" name="user_firstname" class="form-control" id="api_otken_auth" value="{{ token_auth }}">
      <em><small>The token auth key may be published but can only be used to GET rates.</small></em>
    </div>
  </div>
  <div class="col-sm-5 col-sm-offset-1 col-xs-12">
    <h4>Integrate the API in less than 5 minutes</h4>
    <p>Get started now by exploring the API
      documentation:</p>
    <a class="btn btn-primary btn-lg" href="{% url 'docs:overview' %}">View the API Docs</a>
  </div>
</div>

{% endblock %}

user/templates/user/carriers.html
{% extends "user/internal.html" %}
{% load staticfiles %}

{% block title %}Carrier Settings - Shippo{% endblock %}

{% block internalmenu %}

<h3 class="text-primary border-bottom">Change your carrier-specific settings</h3>
<div class="margin-tb-sm">
  {% if success %}
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>Your changes have been saved successfully.</strong>
    </div>
  {% endif %}
  {% if endicia_success %}
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <strong>Your Endicia account has been created successfully. You will receive your account number via email. Please save the account number in your Shippo USPS settings on this page after you have received the mail.</strong>
    </div>
  {% endif %}
  {% if apiuser.ups_production %}
    {% if not apiuser.ups_set %}
      <div class="alert alert-error margin-b-sm">
        <strong><i class="fa fa-exclamation-circle"></i> Warning: Your UPS account is set to production but relevant data is invalid or incomplete.</strong><br>Please verify by clicking on "Edit" below or contact info@goshippo.com.
      </div>
    {% endif %}
  {% endif %}
  {% if apiuser.fedex_production %}
    {% if not apiuser.fedex_set %}
      <div class="alert alert-error margin-b-sm">
        <strong><i class="fa fa-exclamation-circle"></i> Warning: Your FedEx account is set to production but relevant data is invalid or incomplete.</strong><br>Please verify by clicking on "Edit" below or contact info@goshippo.com.
      </div>
    {% endif %}
  {% endif %}
  {% if apiuser.endicia_production %}
    {% if not apiuser.endicia_set %}
      <div class="alert alert-error margin-b-sm">
        <strong><i class="fa fa-exclamation-circle"></i> Warning: Your Endicia account is set to production but relevant data is invalid or incomplete.</strong><br>Please verify by clicking on "Edit" below or contact info@goshippo.com.
      </div>
    {% endif %}
  {% endif %}
  {% if apiuser.parcel2go_production %}
    {% if not apiuser.parcel2go_set %}
      <div class="alert alert-error margin-b-sm">
        <strong><i class="fa fa-exclamation-circle"></i> Warning: Your Parcel2Go account is set to production but relevant data is invalid or incomplete.</strong><br>Please verify by clicking on "Edit" below or contact info@goshippo.com.
      </div>
    {% endif %}
  {% endif %}
  {% if apiuser.dhl_production %}
    {% if not apiuser.dhl_set %}
      <div class="alert alert-error margin-b-sm">
        <strong><i class="fa fa-exclamation-circle"></i> Warning: Your DHL business account is set to production but relevant data is invalid or incomplete.</strong><br>Please verify by clicking on "Edit" below or contact info@goshippo.com.
      </div>
    {% endif %}
  {% endif %}
  <div class="row">

      <div class="col-md-4 col-xs-6 text-center">
        <div class="alert alert-default">
          <div class="lh-100">
            <img src="{% static 'providers/100/FedEx.png' %}">
          </div>
          <div class="carrier-settings">
            {% if apiuser.fedex_production %}
              <div class="margin-v-sm">
                <h4><i class="fa fa-check"></i> Active</h4>
              </div>
              <div>
                <a class="btn btn-blue" href="{% url 'user:usercarriersfedex' %}">Edit</a>
              </div>
            {% else %}
              <div class="margin-v-sm">
                <h4><span class="text-grey"><i class="fa fa-times"></i> Inactive</span></h4>
              </div>
              <div>
                <a class="btn btn-primary" href="{% url 'user:usercarriersfedex' %}">Edit Settings</a>
              </div>
            {% endif %}
          </div>
        </div>
      </div>

      <div class="col-md-4 col-xs-6 text-center">
        <div class="alert alert-default">
          <div class="lh-100">
            <img src="{% static 'providers/100/UPS.png' %}">
          </div>
          <div class="carrier-settings">
            {% if apiuser.ups_production %}
              <div class="margin-v-sm">
                <h4><i class="fa fa-check"></i> Active</h4>
              </div>
              <div>
                <a class="btn btn-blue" href="{% url 'user:usercarriersups' %}">Edit</a>
              </div>
            {% else %}
              <div class="margin-v-sm">
                <h4><span class="text-grey"><i class="fa fa-times"></i> Inactive</span></h4>
              </div>
              <div>
                <a class="btn btn-primary" href="{% url 'user:usercarriersups' %}">Edit Settings</a>
              </div>
            {% endif %}
          </div>
        </div>
      </div>

      <div class="col-md-4 col-xs-6 text-center">
        <div class="alert alert-default">
          <div class="lh-100">
            <img src="{% static 'providers/100/USPS.png' %}">
          </div>
          <div class="carrier-settings">
            {% if apiuser.endicia_production %}
              <div class="margin-v-sm">
                <h4><i class="fa fa-check"></i> Active</h4>
              </div>
              <div>
                <a class="btn btn-blue" href="{% url 'user:usercarriersusps' %}">Edit</a>
              </div>
            {% else %}
              <div class="margin-v-sm">
                <h4><span class="text-grey"><i class="fa fa-times"></i> Inactive</span></h4>
              </div>
              <div>
                <a class="btn btn-primary" href="{% url 'user:usercarriersusps' %}">Edit Settings</a>
              </div>
            {% endif %}
          </div>
        </div>
      </div>

  </div>
  <div class="row">

      <div class="col-md-4 col-xs-6 text-center">
        <div class="alert alert-default">
          <div class="lh-100">
            <img src="{% static 'providers/100/Parcel2Go.png' %}">
          </div>
          <div class="carrier-settings">
            {% if apiuser.parcel2go_production %}
              <div class="margin-v-sm">
                <h4><i class="fa fa-check"></i> Active</h4>
              </div>
              <div>
                <a class="btn btn-blue" href="{% url 'user:usercarriersparcel2go' %}">Edit</a>
              </div>
            {% else %}
              <div class="margin-v-sm">
                <h4><span class="text-grey"><i class="fa fa-times"></i> Inactive</span></h4>
              </div>
              <div>
                <a class="btn btn-primary" href="{% url 'user:usercarriersparcel2go' %}">Edit Settings</a>
              </div>
            {% endif %}
          </div>
        </div>
      </div>

      <div class="col-md-4 col-xs-6 text-center">
        <div class="alert alert-default">
          <div class="lh-100">
            <img src="{% static 'providers/100/Deutsche_Post_DHL.png' %}">
          </div>
          <div class="carrier-settings">
            {% if apiuser.dp_dhl_production or apiuser.dhl_production %}
              <div class="margin-v-sm">
                <h4><i class="fa fa-check"></i> Active</h4>
              </div>
              <div>
                <a class="btn btn-blue" href="{% url 'user:usercarriersdeutschepostdhl' %}">Edit</a>
              </div>
            {% else %}
              <div class="margin-v-sm">
                <h4><span class="text-grey"><i class="fa fa-times"></i> Inactive</span></h4>
              </div>
              <div>
                <a class="btn btn-primary" href="{% url 'user:usercarriersdeutschepostdhl' %}">Edit Settings</a>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>

{% if modal %}
<script type="text/javascript">
  $(window).load(function(){
    $('#carrier-settings-modal').modal('show');
  });
  $('#carrier-settings-modal').on('hidden.bs.modal', function (e) {
    // maybe in the future remove the /CARRIERNAME/ when closing modal
  })
</script>
{% endif %}

<div id="carrier-settings-modal" class="modal" role="dialog" aria-labelledby="carrier-detailed-settings" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">{% block modaltitle %}{% endblock %}</h4>
      </div>
      <div class="modal-body">
        {% block modalbody %}{% endblock %}
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

{% endblock %}

user/templates/user/internal.html
{% extends "base.html" %}

{% block content %}

<div class="container page-inner">
    <div class="panel panel-default clearfix">
      	<div class="panel-heading">
        	<div class="row">
				<div class="col-sm-3 hidden-xs hidden-sm">
					<h3 class="panel-title lh-40">
						{% if user.first_name and user.last_name %}
							{{ user.first_name }} {{ user.last_name }}
						{% else %}
							{{ user.email }}
						{% endif %}
					</h3>
				</div>
				<div class="col-md-9 col-sm-12 col-xs-12 text-right">
					<ul class="nav nav-tabs nav-tabs-panel pull-right border-none">
						<li{% if urlname == 'userdashboard' %} class="active"{% endif %}><a href="{% url 'user:userdashboard' %}">Dashboard</a></li>
						{% if shopify %}
							<li{% if urlname == 'userorders' %} class="active"{% endif %}><a href="{% url 'user:userorders' %}">Orders</a></li>
						{% endif %}
						<li{% if urlname == 'usercarriers' %} class="active"{% endif %}><a href="{% url 'user:usercarriers' %}">Carriers</a></li>
						<li{% if urlname == 'userapikeys' %} class="active"{% endif %}><a href="{% url 'user:userapikeys' %}">API Keys</a></li>
						<li{% if urlname == 'userbilling' %} class="active"{% endif %}><a href="{% url 'user:userbilling' %}">Billing</a></li>
						<li{% if urlname == 'userprofile' %} class="active"{% endif %}><a href="{% url 'user:userprofile' %}">Account</a></li>
					</ul>
				</div>
			</div>
      	</div>
		<div class="panel-body">
			{% if not apiuser.address.all_required_data or not apiuser.billing.stripe_authorized %}
				<div class="alert alert-warning alert-dismissable">
				    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			    	<i class="fa fa-exclamation-triangle"></i>
			    	<strong>
			    	{% if not apiuser.address.all_required_data or not apiuser.address.zip %}
			    		{%  if not apiuser.billing.stripe_authorized %}
			    			In order to get rates and shipping labels, you need to enter your address and billing data.
			    			</strong>&nbsp;&nbsp;&nbsp;
			    			<a href="{% url 'user:userprofile' %}" class="btn btn-sm btn-blue"><i class="fa fa-chevron-right"></i> Enter address now</a>
			    			&nbsp;&nbsp;&nbsp;<a href="{% url 'user:userbilling' %}" class="btn btn-sm btn-blue"><i class="fa fa-chevron-right"></i> Enter billing data now</a>
			    		{% else %}
			    			In order to get rates and shipping labels, you need to enter your address.
			    			</strong>&nbsp;&nbsp;&nbsp;
			    			<a href="{% url 'user:userprofile' %}" class="btn btn-sm btn-blue"><i class="fa fa-chevron-right"></i> Enter address now</a>
			    		{% endif %}
			    	{% else %}
			    		{%  if not apiuser.billing.stripe_authorized %}
			    			In order to get rates and shipping labels, you need to enter your billing data.
			    			</strong>&nbsp;&nbsp;&nbsp;
			    			&nbsp;&nbsp;&nbsp;<a href="{% url 'user:userbilling' %}" class="btn btn-sm btn-blue"><i class="fa fa-chevron-right"></i> Enter billing data now</a>
			    		{% endif %}
			    	{% endif %}

				</div>
			{% endif %}
			{% block internalmenu %}{% endblock %}
		</div>
	</div>
</div>

{% endblock %}

{% block javascript_footer %}
  {{ block.super }}
  <script type="text/javascript">
    //set Mixpanel distinct user id = username = email
    mixpanel.identify("{{ apiuser.user.email }}");
  </script>
{% endblock %}