api/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

# for API
from rest_framework.urlpatterns import format_suffix_patterns
from api import views
from django.conf.urls import include

UUID_REGEX_PATTERN = '([a-fA-F0-9]{32}|[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12})'

urlpatterns = patterns('',
    url(r'^addresses/$', views.AddressList.as_view()),
    url(r'^addresses/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.AddressDetail.as_view()),
    
    url(r'^addresses/(?P<address_id>' + UUID_REGEX_PATTERN + '+)/locations/$', views.LocationList.as_view()),
    url(r'^locations/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.LocationDetail.as_view()),
    url(r'^locations/$', views.LocationList.as_view()),
    
    url(r'^parcels/$', views.ParcelList.as_view()),
    url(r'^parcels/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.ParcelDetail.as_view()),

    url(r'^shipments/$', views.ShipmentList.as_view()),
    url(r'^shipments/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.ShipmentDetail.as_view()),
    
    url(r'^shipments/(?P<shipment_id>' + UUID_REGEX_PATTERN + '+)/rates(?:/(?P<currency_iso>([A-Za-z]{3})))?/$', views.RateList.as_view()),
    url(r'^rates/$', views.RateList.as_view()),
    url(r'^rates/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.RateDetail.as_view()),
    
    url(r'^transactions/$', views.TransactionList.as_view()),
    url(r'^transactions/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.TransactionDetail.as_view()),
    
    url(r'^transactions/(?P<transaction_id>' + UUID_REGEX_PATTERN + '+)/tracking/$', views.TrackingList.as_view()),
    url(r'^tracking/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.TrackingDetail.as_view()),
    url(r'^tracking/$', views.TrackingList.as_view()),
)

urlpatterns = format_suffix_patterns(urlpatterns)

urlpatterns += patterns('',
    url(r'^auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
)

cms/urls.py
from django.conf.urls import patterns, url
from cms import views
from django.views.generic import TemplateView
from django.shortcuts import redirect

urlpatterns = patterns('',
    url(r'^$', views.displayHomePage, name='homepage'),
    url(r'^integrate/(?P<carrier>[a-zA-Z0-9_.-]+)/$', views.displayCarrierAdLandingPge, name='carrieradlandingpage'),
    url(r'^api/$', views.displayAPILandingPage, name='apilandingpage'),
    url(r'^partner/$', views.displayBecomePartnerPage, name='becomepartnerpage'),
    url(r'^couriers/$', views.displayCouriersPage, name='courierspage'),
    url(r'^demo/$', views.displayDemoPage, name='demopage'),
    url(r'^pricing/$', views.displayPricingPage, name='pricingpage'),
    url(r'^faq/$', TemplateView.as_view(template_name='page_singledesigns/faq.html'), name="faqpage"),
    url(r'^contact-us/$', views.displayContactUsPage, name='contactuspage'),
    url(r'^sitemap/$', views.displaySitemapPage, name='sitemappage'),
    url(r'^jobs/$', TemplateView.as_view(template_name='page_singledesigns/jobs.html'), name="jobspage"),
    url(r'^terms-service/$', TemplateView.as_view(template_name='page_singledesigns/terms_service.html'), name="termsservicepage"),
    url(r'^privacy-policy/$', TemplateView.as_view(template_name='page_singledesigns/privacy_policy.html'), name="privacypolicypage"),
    url(r'^list-of-prohibited-items/$', TemplateView.as_view(template_name='page_singledesigns/list-of-prohibited-items.html'), name="prohibiteditemspage"),
    url(r'^internal/helpers/sendajaxmail/$', views.sendAJAXMail, name='sendajaxmail'),
    url(r'^blog/$', views.displayBlogpage, name='blogpage'),
    url(r'^blog/(?P<slug>[a-zA-Z0-9_.-]+)/$', views.displayBlogpost, name='blogpost'),
)

#redirect old blog posts for Google crawler
urlpatterns += patterns('',
    url(r'^local-post-office-vs-private-shipping-provider/$', lambda x: redirect('/blog/local-post-office-vs-private-shipping-provider/')),
    url(r'^can-e-commerce-stores-offer-free-shipping/$', lambda x: redirect('/blog/can-e-commerce-stores-offer-free-shipping/')),
    url(r'^finding-right-shipping-packaging-business/$', lambda x: redirect('/blog/finding-right-shipping-packaging-business/')),
    url(r'^guide-selling-pinterest/$', lambda x: redirect('/blog/guide-selling-pinterest/')),
    url(r'^amazon-prime-air-amazon-drones-late-game/$', lambda x: redirect('/blog/amazon-prime-air-amazon-drones-late-game/')),
    url(r'^promote-online-store/$', lambda x: redirect('/blog/promote-online-store/')),
    url(r'^get-e-commerce-business-ground/$', lambda x: redirect('/blog/get-e-commerce-business-ground/')),
    url(r'^fulfilment-crowdfunding-projects/$', lambda x: redirect('/blog/fulfilment-crowdfunding-projects/')),
    url(r'^sending-holiday-gifts-time/$', lambda x: redirect('/blog/sending-holiday-gifts-time/')),
    url(r'^shipping-difficulties-marketplace-sellers/$', lambda x: redirect('/blog/shipping-difficulties-marketplace-sellers/')),
    url(r'^save-50-sending-small-parcels-internationally-germany/$', lambda x: redirect('/blog/save-50-sending-small-parcels-internationally-germany/')),
    url(r'^find-sign-up-right-ups-account/$', lambda x: redirect('/blog/find-sign-up-right-ups-account/')),
    url(r'^find-sign-up-right-fedex-account/$', lambda x: redirect('/blog/find-sign-up-right-fedex-account/')),
    url(r'^print-gls-postage-labels/$', lambda x: redirect('/blog/print-gls-postage-labels/')),
    url(r'^print-hermes-postage-labels/$', lambda x: redirect('/blog/print-hermes-postage-labels/')),
    url(r'^obtain-posti-postage-labels/$', lambda x: redirect('/blog/obtain-posti-postage-labels/')),
    url(r'^print-deutsche-post-postage-labels/$', lambda x: redirect('/blog/print-deutsche-post-postage-labels/')),
    url(r'^print-posten-sweden-postage-labels/$', lambda x: redirect('/blog/print-posten-sweden-postage-labels/')),
    url(r'^obtain-posten-norge-postage-labels/$', lambda x: redirect('/blog/obtain-posten-norge-postage-labels/')),
    url(r'^print-royal-mail-postage-labels/$', lambda x: redirect('/blog/print-royal-mail-postage-labels/')),
    url(r'^hurdles-smes-international-logistics/$', lambda x: redirect('/blog/hurdles-smes-international-logistics/')),
    url(r'^can-e-commerce-businesses-offer-free-shipping/$', lambda x: redirect('/blog/can-e-commerce-businesses-offer-free-shipping/')),
    url(r'^hurdles-smes-international-logistics/$', lambda x: redirect('/blog/hurdles-smes-international-logistics/')),
    url(r'^2013-year-shipping-startups/$', lambda x: redirect('/blog/2013-year-shipping-startups/')),
    url(r'^drop-shipping-expert/$', lambda x: redirect('/blog/drop-shipping-expert/')),
    url(r'^drop-shipping-step-by-step/$', lambda x: redirect('/blog/drop-shipping-step-by-step/')),
    url(r'^the-myth-of-rocket-mail/$', lambda x: redirect('/blog/the-myth-of-rocket-mail/')),
)

shippo/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import RedirectView
from cms.sitemap import *
from cms import views
from django.views.generic import TemplateView

admin.autodiscover()

# a dictionary of sitemaps
sitemaps = {
    'design_pages': DesignPagesSitemap,
    'carrier_pages': CarrierContentSitemap,
    'logistics_pages': SEOPagesSitemap,
    'blog_posts': BlogPostsSitemap,
}

handler404 = 'cms.views.display404Page'
handler500 = 'cms.views.display500Page'

urlpatterns = patterns('',
    url(r'^admin/?', include(admin.site.urls)),
    url(r'^shopify/', include('shopify_app.urls', namespace="shopify_app")),
    url(r'^etsy/', include('etsy_app.urls', namespace="etsy_app")),
    url(r'^', include('user.urls', namespace="user")),
    url(r'^', include('cms.urls', namespace="cms")),
    url(r'^', include('websearch.urls', namespace="websearch")),
    #url(r'^v1/', include('api.urls')),
    url(r'^docs/', include('docs.urls', namespace="docs")),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
)

# General redirect to seopage for all others
urlpatterns += patterns('',
    url(r'^(?P<slug>[a-zA-Z0-9_.-]+)/$', views.displaySEOPage, name='seopage'),
)

#General redirect to docs from root
#urlpatterns += patterns('',
    #url(r'^$', lambda x: redirect('https://goshippo.com')),
#)

cms/views.py
from django.shortcuts import render
from django.template import Template, Context
from cms.models import *
from adapter.models import Provider
from django.shortcuts import redirect, get_object_or_404
from django.template.defaultfilters import slugify
from django.core.mail import send_mail, BadHeaderError
from django.conf import settings
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def displayHomePage(request):
	context = {}
	return render(request, 'page_singledesigns/home.html', context)

def displayCarrierAdLandingPge(request, carrier):
	context = {'carrier':carrier}
	return render(request, 'page_singledesigns/home.html', context)

def displayDemoPage(request):
	context = {}
	return render(request, 'page_singledesigns/demo.html', context)

def displayPricingPage(request):
	context = {}
	return render(request, 'page_singledesigns/pricing.html', context)

def displaySEOPage(request, slug):
	all_carriers = Provider.objects.all()
	for carrier in all_carriers:
		if slugify(slug) == slugify(carrier.name):
			carrier_content = CarrierContent.objects.get(carrier=carrier)
			seopages = SEOPage.objects.filter(carrier_content=carrier_content)
			context = {'carrier_content': carrier_content, 'seopages': seopages}
			return render(request, 'page_types/carrier-overview.html', context)
	seo_page = get_object_or_404(SEOPage, slug=slug)
	context = {'seopage': seo_page}
	return render(request, 'page_types/seopage.html', context)

def displayBlogpage(request):
	all_posts = Blogpost.objects.order_by('-pub_date')
	paginator = Paginator(all_posts, 10)
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		posts = paginator.page(paginator.num_pages)
	context = {'posts': posts,}
	return render(request, 'page_types/blog.html', context)

def displayBlogpost(request, slug):
	blog_post = get_object_or_404(Blogpost, slug=slug)
	content_as_template = Template('{% load staticfiles %}' + blog_post.body_html)
	content = content_as_template.render(Context(''))
	context = {'post': blog_post, 'content': content}
	return render(request, 'page_types/blogpost.html', context)

def displayAPILandingPage(request):
	mail_subject = 'Shippo: Your API Access Information'
	message_body = 'New API registration (/api):'
	success, error = mail_name_inline_form(request, mail_subject, message_body)
	context = {'success': success, 'error': error}
	return render(request, 'page_singledesigns/api.html', context)

def displayBecomePartnerPage(request):
	mail_subject = 'Shippo: Your Carrier Access Information'
	message_body = 'New registration as carrier (/partner):'
	success, error = mail_name_inline_form(request, mail_subject, message_body)
	context = {'success': success, 'error': error}
	return render(request, 'page_singledesigns/become_partner.html', context)

def displayCouriersPage(request):
	all_carriers = CarrierContent.objects.filter(overview_enabled=True)
	context = {'carriers': all_carriers}
	return render(request, 'page_singledesigns/couriers.html', context)

def mail_name_inline_form(request, mail_subject, message_body=''):
	success = False
	error = False
	if request.method == 'POST':
		try:
			fullname = request.POST['fullname']
			email = request.POST['email']
			if email:
				try:
					subject = mail_subject
					message = message_body + ' Full name: ' + str(fullname) + ', E-mail: ' + str(email)
					to_mail = settings.DEFAULT_CONTACT_EMAIL
					send_mail(subject, message, email, [to_mail], fail_silently=True)
				except BadHeaderError:
					error = 'There was a problem submitting your registration. Please try again or contact us directly at info@goshippo.com. Sorry for the trouble!'
			else:
				error = 'It seems like you have not entered all required data. Please try again or contact us directly at info@goshippo.com. Sorry for the trouble!'
			if error == False:
				success = True
		except KeyError:
			error = 'There was a problem submitting your registration. Please try again or contact us directly at info@goshippo.com. Sorry for the trouble!'
	return success, error

def sendAJAXMail(request, from_email='ajaxmail@goshippo.com'):
	if request.method == 'POST':
		subject = request.POST['subject']
		message = request.POST['message']
		from_mail = from_email
		to_mail = settings.FRONTEND_ERROR_CONTACT_EMAIL
		send_mail(subject, message, from_mail, [to_mail], fail_silently=True)
		return HttpResponse('Success')

def displaySitemapPage(request):
	content_carriers = CarrierContent.objects.filter(overview_enabled=True)
	seopages = SEOPage.objects.all()
	context = {'content_carriers': content_carriers, 'seopages': seopages}
	return render(request, 'page_singledesigns/sitemap.html', context)

def displayContactUsPage(request):
	success = False
	error = False
	to_mail = settings.DEFAULT_CONTACT_EMAIL
	if request.method == 'POST':
		try:
			fullname = request.POST['fullname']
			email = request.POST['email']
			message = request.POST['message']
			if message and email:
				try:
					subject = 'Shippo: New Contact Form Submission'
					send_mail(subject, message, email, [to_mail], fail_silently=True)
				except BadHeaderError:
					error = 'There was a problem sending your message. Please try again or contact us directly at info@goshippo.com. Sorry for the trouble!'
			else:
				error = 'It seems like you have not entered all required data. Please try again or contact us directly at info@goshippo.com. Sorry for the trouble!'
			if error == False:
				success = True
		except KeyError:
			error = 'There was a problem sending your message. Please try again or contact us directly at info@goshippo.com. Sorry for the trouble!'
	context = {'success': success,'error': error}
	return render(request, 'page_singledesigns/contact-us.html', context)

def display404Page(request):
	context = {}
	return render(request, 'cms-404.html', context)

def display500Page(request):
	context = {}
	return render(request, 'cms-500.html', context)

cms/templates/page_singledesigns/faq.html
{% extends "base.html" %}

{% block title %}Frequently Asked Questions and Answers - Shippo{% endblock %}

{% block content %}

<div class="container page-inner">
	<div class="text-center">
		<h1 class="serif">Frequently Asked Questions</h1>
		<p class="lead">Shippo finds the best rates for your small parcel shipments. We compare all courier companies and help you find the cheapest, fastest or best options.</p>
	</div>

	<div id="faq-overview">
		<div class="container">
			<div id="faq-general-q" class="panel panel-default clearfix">
				<div class="panel-heading">
					<h3 class="panel-title">General</h3>
				</div>
				<div class="panel-body">
					<p><a href="#general-shippo">What is Shippo?</a></p>
					<p><a href="#general-shipper">Is Shippo shipping my parcel?</a></p>
					<p><a href="#general-couriers">The rates of a courier company are missing!</a></p>
					<p><a href="#general-accuracy">How accurate are the details of the rates shown?</a></p>
					<p><a href="#general-liablity">Who is liable if anything goes wrong?</a></p>
					<p><a href="#general-discounts">Can I use my own discount rates with Shippo?</a></p>
					<p><a href="#general-legal">Is Shippo allowed to show and offer these rates?</a></p>
					<p><a href="#general-comparison">Why are some shipping rates different from the rates I have seen elsewhere?</a></p>
					<p><a href="#general-accessorial">What happens if a courier charges additional fees after the label purchase?</a></p>
				</div>
			</div>
			<div id="faq-websearch-q" class="panel panel-default clearfix">
				<div class="panel-heading">
					<h3 class="panel-title">Shippo Web Search</h3>
				</div>
				<div class="panel-body">
					<p><a href="#webserch-labels">Can I purchase shipping labels directly on Shippo?</a></p>
					<p><a href="#webserch-pay">Do I have to pay to use the Shippo web search?</a></p>
				</div>
			</div>
			<div id="faq-api-q" class="panel panel-default clearfix">
				<div class="panel-heading">
					<h3 class="panel-title">Shippo API</h3>
				</div>
				<div class="panel-body">
					<p><a href="#api-about">What is the Shippo API?</a></p>
					<p><a href="#api-labels">Can I purchase shipping labels with the Shippo API?</a></p>
					<p><a href="#api-settings">What options does the Shippo API offer?</a></p>
					<p><a href="#api-libraries">What libraries are available?</a></p>
					<p><a href="#webserch-pay">Do I have to pay to use the Shippo API?</a></p>
				</div>
			</div>
		</div>
	</div>
	<br>
	<hr>
	<br><br>
	<div id="faq-answers">
		<div class="container">
			<div id="faq-general-a" class="panel panel-default clearfix">
				<div class="panel-heading">
					<h3 class="panel-title">General</h3>
				</div>
				<div class="panel-body">
					<p><a class="link-black no-hover" name="general-shippo"><strong>What is Shippo?</strong></a><br>
					Shippo finds the best rates for your small parcel shipments. We compare all courier companies and help you find the cheapest, fastest or best options.</p>
					<p><a class="link-black no-hover" name="general-shipper"><strong>Is Shippo shipping my parcel?</strong></a><br>
					No. Shippo’s mission is to find and show the best rates available for your shipments. At no point will we become involved in shipping your parcel itself. You will always find the best rates on Shippo, but your contract will always be directly with the courier company.</p>
					<p><a class="link-black no-hover" name="general-couriers"><strong>The rates of a courier company are missing!</strong></a><br>
					We are constantly expanding our database of shipment providers and rates. If you have found a better rate somewhere else, please let us know at <a href="mailto:info@goshippo.com">info@goshippo.com</a> and we will prioritize the integration of this courier company for you.</p>
					<p><a class="link-black no-hover" name="general-accuracy"><strong>How accurate are the details of the rates shown?</strong></a><br>
					Shippo integrates all courier rates with care; all information have been validated several times. However, please note that even the courier company is often only able to give estimates. Transit times, for example, often depend on many aspects and thus may vary. All information displayed on Shippo are official courier information and provide the best estimation possible.</p>
					<p><a class="link-black no-hover" name="general-liablity"><strong>Who is liable if anything goes wrong?</strong></a><br>
					Shippo does never become part of your contract with the courier company. Therefore, you need to contact the courier company for any arising claims. We are happy to assist you with any problems you might have, of course!</p>
					<p><a class="link-black no-hover" name="general-discounts"><strong>Can I use my own discount rates with Shippo?</strong></a><br>
					Whenever possible, Shippo allows you to use your own account numbers and use your discount rates. You are free to use other rates, of course!</p>
					<p><a class="link-black no-hover" name="general-legal"><strong>Is Shippo allowed to show and offer these rates?</strong></a><br>
					All rates are official rates of the corresponding courier company that are publicly available and that we are allowed to offer on our website. We will not become part of your shipping agreement with the courier company and thus only serve as the information gateway to your shipment needs.</p>
					<p><a class="link-black no-hover" name="general-comparison"><strong>Why are some shipping rates different from the rates I have seen elsewhere?</strong></a><br>
					Like airline tickets, shipping prices are not static. In many cases, Shippo is able to offer better prices than those available on the courier service’s website itself.</p>
					<p><a class="link-black no-hover" name="general-accessorial"><strong>What happens if a courier charges additional fees after the label purchase?</strong></a><br>
					Some couriers charge additional fees (called “accessorial charges”) after you have purchased a label; these fees can include, for example, fees for correcting the recipient’s address or for parcels that have been larger than described. We will let you know about these fees transparently and instantly and then charge the amount from your credit card.</p>
				</div>
			</div>
			<div id="faq-websearch-q" class="panel panel-default clearfix">
				<div class="panel-heading">
					<h3 class="panel-title">Shippo Web Search</h3>
				</div>
				<div class="panel-body">
					<p><a class="link-black no-hover" name="webserch-labels"><strong>Can I purchase shipping labels directly on Shippo?</strong></a><br>
					Labels of certain courier services can be purchased directly on Shippo. For other courier services, you need an own account number to obtain your label. In some rare cases, the label generation is not available at all. You will find detailed instructions on how to send your parcel in these cases.</p>
					<p><a class="link-black no-hover" name="webserch-pay"><strong>Do I have to pay to use the Shippo web search?</strong></a><br>
					You can use Shippo’s web search for free, anytime, for as often as you want to. Zero costs. We wil only charge a small service fee for labels you obtain on Shippo.</p>
				</div>
			</div>
			<div id="faq-api-q" class="panel panel-default clearfix">
				<div class="panel-heading">
					<h3 class="panel-title">Shippo API</h3>
				</div>
				<div class="panel-body">
					<p><a class="link-black no-hover" name="api-about"><strong>What is the Shippo API?</strong></a><br>
					With the Shippo API, you can integrate all of Shippo’s functionality in your own web application. The API will find the best rates for any shipment you need. Perfect use cases, for instance, include shopping platforms or e-commerce stores. You are able to display all available rates, auto-select rates, print labels and charge your customers or sellers through our API.</p>
					<p><a class="link-black no-hover" name="api-labels"><strong>Can I purchase shipping labels with the Shippo API?</strong></a><br>
					Labels of certain courier services can be purchased with our API. For other courier services, you need an own account number to obtain your label. In some rare cases, the label generation is not available at all. You will receive detailed instructions on how to send your parcel in these cases.</p>
					<p><a class="link-black no-hover" name="api-settings"><strong>What options does the Shippo API offer?</strong></a><br>
					You can completely adapt the Shippo API to your needs. If you want, the API will only show rates with pickup service available, for instance. You can find all settings in the API documentation.</p>
					<p><a class="link-black no-hover" name="api-libraries"><strong>What libraries are available?</strong></a><br>
					The Shippo API is available for many programming languages. Please find an overview of all libraries in the API documentation.</p>
					<p><a class="link-black no-hover" name="webserch-pay"><strong>Do I have to pay to use the Shippo API?</strong></a><br>
					We charge a fee of 30 cents for each label you generate with our API. </p>
				</div>
			</div>
		</div>
	</div>

	<div id="faq-unanswered">
		<div class="container text-center">
			<h4>Is your question still unanswered? <a href="{% url 'cms:contactuspage' %}">Contact us now, we are happy to help!</a></h4>
		</div>
	</div>

</div>

{% include "page_elements/prefooter_getstarted.html" %}

{% endblock %}

cms/templates/page_singledesigns/sitemap.html
{% extends "base.html" %}

{% block title %}Sitemap - Shippo{% endblock %}

{% block content %}

<div class="container page-inner">
	<h1>Sitemap</h1>
	<div class="row">
		<div class="col-sm-4 col-xs-12">
			<h4>About Shippo</h4>
			<ul class="list-noblt">
				<li><a href="{% url 'cms:homepage' %}" title="Compare and find the best express shipping rates">Home</a></li>
				<li><a href="{% url 'cms:apilandingpage' %}" title="How Shippo works: the API to make shipping easy and affordable">API</a></li>
				<li><a href="{% url 'cms:demopage' %}" title="Try the Shippo API: the API to make shipping easy and affordable">Demo</a></li>
				<li><a href="{% url 'cms:pricingpage' %}" title="Pricing of the Shippo API: the API to make shipping easy and affordable">Pricing</a></li>
				<li><a href="{% url 'docs:overview' %}" title="Docs of the Shippo API: the API to make shipping easy and affordable">Docs</a></li>
				<li><a href="{% url 'cms:courierspage' %}" title="Pricing of Shippo; the API to make shipping easy and affordable">Supported Couriers</a></li>
				<li><a href="{% url 'cms:becomepartnerpage' %}" title="Shippo Blog: the API to make shipping easy and affordable">Become a Partner</a></li>
				<li><a href="{% url 'cms:blogpage' %}" title="Contact Shippo: the API to make shipping easy and affordable">Blog</a></li>
				<li><a href="{% url 'cms:contactuspage' %}" title="Contact Shippo: the API to make shipping easy and affordable">Contact Us</a></li>
				<li><a href="{% url 'cms:jobspage' %}" title="Jobs at Shippo: the API to make shipping easy and affordable">Jobs</a></li>
				<li><a href="{% url 'cms:sitemappage' %}" title="Shippo Sitemap; the API to make shipping easy and affordable">Sitemap</a></li>
				<li><a href="{% url 'cms:privacypolicypage' %}" title="Shippo Sitemap; the API to make shipping easy and affordable">Privacy Policy</a></li>
				<li><a href="{% url 'cms:termsservicepage' %}" title="Shippo Sitemap; the API to make shipping easy and affordable">Terms of Service</a></li>
			</ul>
		</div>
		<div class="col-sm-4 col-xs-12">
			<h4>Carriers</h4>
			<ul class="list-noblt">
				{% for content_carrier in content_carriers %}
					<li><a href="/{{ content_carrier.slug }}" title="{{ content_carrier.title }}">{{ content_carrier.carrier.name }}</a></li>
				{% endfor %}
			</ul>
		</div>
		<div class="col-sm-4 col-xs-12">
			<h4>About Shipping</h4>
			<ul class="list-noblt">
				{% for seopage in seopages %}
					<li><a href="/{{ seopage.slug }}" title="{{ seopage.title }}">{{ seopage.title }}</a></li>
				{% endfor %}
			</ul>
		</div>
	</div>

</div>

{% endblock %}