api/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

# for API
from rest_framework.urlpatterns import format_suffix_patterns
from api import views
from django.conf.urls import include

UUID_REGEX_PATTERN = '([a-fA-F0-9]{32}|[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12})'

urlpatterns = patterns('',
    url(r'^addresses/$', views.AddressList.as_view()),
    url(r'^addresses/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.AddressDetail.as_view()),
    
    url(r'^addresses/(?P<address_id>' + UUID_REGEX_PATTERN + '+)/locations/$', views.LocationList.as_view()),
    url(r'^locations/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.LocationDetail.as_view()),
    url(r'^locations/$', views.LocationList.as_view()),
    
    url(r'^parcels/$', views.ParcelList.as_view()),
    url(r'^parcels/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.ParcelDetail.as_view()),

    url(r'^shipments/$', views.ShipmentList.as_view()),
    url(r'^shipments/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.ShipmentDetail.as_view()),
    
    url(r'^shipments/(?P<shipment_id>' + UUID_REGEX_PATTERN + '+)/rates(?:/(?P<currency_iso>([A-Za-z]{3})))?/$', views.RateList.as_view()),
    url(r'^rates/$', views.RateList.as_view()),
    url(r'^rates/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.RateDetail.as_view()),
    
    url(r'^transactions/$', views.TransactionList.as_view()),
    url(r'^transactions/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.TransactionDetail.as_view()),
    
    url(r'^transactions/(?P<transaction_id>' + UUID_REGEX_PATTERN + '+)/tracking/$', views.TrackingList.as_view()),
    url(r'^tracking/(?P<object_id>' + UUID_REGEX_PATTERN + '+)/$', views.TrackingDetail.as_view()),
    url(r'^tracking/$', views.TrackingList.as_view()),
)

urlpatterns = format_suffix_patterns(urlpatterns)

urlpatterns += patterns('',
    url(r'^auth/', include('rest_framework.urls',
                               namespace='rest_framework')),
)

docs/urls.py
from django.conf.urls import patterns, url
from docs import views

urlpatterns = patterns('',
    url(r'^$', views.APIDocsOverview, name='overview'),
    url(r'^addresses/$', views.APIDocsAddresses, name='addresses'),
    url(r'^parcels/$', views.APIDocsParcels, name='parcels'),
    url(r'^shipments/$', views.APIDocsShipments, name='shipments'),
    url(r'^rates/$', views.APIDocsRates, name='rates'),
    url(r'^transactions/$', views.APIDocsTransactions, name='transactions'),
    url(r'^billing/$', views.APIDocsBilling, name='billing'),
    url(r'^testing/$', views.APIDocsTesting, name='testing'),
)

shippo/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import RedirectView
from cms.sitemap import *
from cms import views
from django.views.generic import TemplateView

admin.autodiscover()

# a dictionary of sitemaps
sitemaps = {
    'design_pages': DesignPagesSitemap,
    'carrier_pages': CarrierContentSitemap,
    'logistics_pages': SEOPagesSitemap,
    'blog_posts': BlogPostsSitemap,
}

handler404 = 'cms.views.display404Page'
handler500 = 'cms.views.display500Page'

urlpatterns = patterns('',
    url(r'^admin/?', include(admin.site.urls)),
    url(r'^shopify/', include('shopify_app.urls', namespace="shopify_app")),
    url(r'^etsy/', include('etsy_app.urls', namespace="etsy_app")),
    url(r'^', include('user.urls', namespace="user")),
    url(r'^', include('cms.urls', namespace="cms")),
    url(r'^', include('websearch.urls', namespace="websearch")),
    #url(r'^v1/', include('api.urls')),
    url(r'^docs/', include('docs.urls', namespace="docs")),
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
)

# General redirect to seopage for all others
urlpatterns += patterns('',
    url(r'^(?P<slug>[a-zA-Z0-9_.-]+)/$', views.displaySEOPage, name='seopage'),
)

#General redirect to docs from root
#urlpatterns += patterns('',
    #url(r'^$', lambda x: redirect('https://goshippo.com')),
#)

docs/models.py
from django.db import models

# Create your models here.

docs/views.py
from django.shortcuts import render
from django.contrib.auth.models import User

def APIDocsOverview(request):
    current_user = request.user
    context = {}
    return render(request, 'overview.html', context)

def APIDocsAddresses(request):
    current_user = request.user
    context = {}
    return render(request, 'addresses.html', context)

def APIDocsParcels(request):
    current_user = request.user
    context = {}
    return render(request, 'parcels.html', context)

def APIDocsShipments(request):
    current_user = request.user
    context = {}
    return render(request, 'shipments.html', context)

def APIDocsRates(request):
    current_user = request.user
    context = {}
    return render(request, 'rates.html', context)

def APIDocsLabels(request):
    current_user = request.user
    context = {}
    return render(request, 'labels.html', context)

def APIDocsTransactions(request):
    current_user = request.user
    context = {}
    return render(request, 'transactions.html', context)

def APIDocsBilling(request):
    current_user = request.user
    context = {}
    return render(request, 'billing.html', context)

def APIDocsTesting(request):
    current_user = request.user
    context = {}
    return render(request, 'apitesting.html', context)

docs/templates/addresses.html
{% extends "docs.html" %}

{% block apicontent %}
<h2>Addresses</h2>

<h4>/addresses/</h4>

<p>Address objects are used for creating Shipments, obtaining Rates and printing Labels, and thus are one of the fundamental building blocks of the Shippo API.</p>

<br><p>API Resource URL: <strong><a href="https://api.goshippo.com/v1/addresses/">https://api.goshippo.com/v1/addresses/</a></strong></p>

<h4>Example Request JSON array</h4>
<div id="pre_request"></div>
<script type="text/javascript">
	var obj = {
			"object_purpose": "QUOTE",
			"name": "Laura Behrens Wu",
		    "company": "Shippo",
		    "street1": "Clayton St.",
		    "street_no": "215",
		    "street2": "",
		    "city": "San Francisco",
		    "state": "CA",
		    "zip": "94117",
		    "country": "US",
		    "phone": "+1 555 341 9393",
		    "email": "laura@goshippo.com",
		    "ip": "",
		    "metadata": "Customer ID 123456"
		};
	var str = JSON.stringify(obj, undefined, 4);
	$('#pre_request').html('<pre>' + GlobalHelpers.PrettyPrintJSON(str) + '</pre>');
</script>

<h4>Example Response JSON array</h4>
<div id="pre_response"></div>
<script type="text/javascript">
	var obj = {
		"object_state": "VALID",
		"object_purpose": "QUOTE",
		"object_source": "FULLY_ENTERED",
		"object_created": "2013-12-11T19:38:09.729Z",
		"object_updated": "2013-12-11T19:38:09.729Z",
		"object_id": "fcd9c72b564d4bfa8c03299ed6545132",
		"object_owner": "tech@goshippo.com",
		"name": "Laura Behrens Wu",
		"company": "Shippo",
		"street1": "Clayton St.",
		"street_no": "215",
		"street2": "",
		"city": "San Francisco",
		"state": "CA",
		"zip": "94117",
		"country": "US",
	    "phone": "+1 555 341 9393",
		"email": "laura@goshippo.com",
		"ip": "",
		"metadata": "Customer ID 123456"
	};
	var str = JSON.stringify(obj, undefined, 4);
	$('#pre_response').html('<pre>' + GlobalHelpers.PrettyPrintJSON(str) + '</pre>');
</script>

<h4>Request Schema</h4>
	<div class="table-responsive">
		<table class="table table-bordered table-hover table-col-1-str">
			<thead class="italic">
				<tr>
					<td width="20%">Key</td>
					<td width="20%">Required</td>
					<td width="20%">Format / Values</td>
					<td>Description</td>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>object_purpose</td>
					<td>required</td>
					<td>"QUOTE"<br>"PURCHASE"</td>
					<td>Quote Addresses can be generated by either passing a complete street address to the Address resource, or by passing only an IP address or a country, plus optionally a ZIP code or a city name. Quote Addresses can only be used for
						obtaining shipping Rate quotes and cannot be used to purchase Labels. Addresses that should be used for purchases must be fully entered, i.e., a complete street address with all required fields must be passed.</td>
				</tr>
				<tr>
					<td>name</td>
					<td>required for purchase</td>
					<td><em>string</em></td>
					<td>First and Last Name of the addressee</td>
				</tr>
				<tr>
					<td>company</td>
					<td>optional</td>
					<td><em>string</em></td>
					<td>Company Name</td>
				</tr>
				<tr>
					<td>street1</td>
					<td>required for purchase</td>
					<td><em>string</em></td>
					<td>First street line, which is usually the street name. Note that a building's street number should be passed separately (see below).</td>
				</tr>
				<tr>
					<td>street_no</td>
					<td>optional</td>
					<td><em>string</em></td>
					<td>Street number of the addressed building. Even though the field is optional (not all addresses contain street numbers), for a physical location that actually has a street number, you should pass it.
					Sending a street number yields more accurate Rates and will result in a more reliable service.</td>
				</tr>
				<tr>
					<td>street2</td>
					<td>optional</td>
					<td><em>string</em></td>
					<td>Second street line.</td>
				</tr>
				<tr>
					<td>city</td>
					<td>required for purchase</td>
					<td><em>string</em></td>
					<td>Name of a city. When creating a Quote Address, sending a city is optional but will yield more accurate Rates. Please bear in mind that city names may be ambiguous (there are 34 Springfields in the US). Passing a state or a ZIP code (see below), if known, will yield more accurate results.</td>
				</tr>
				<tr>
					<td>zip</td>
					<td>required for purchase</td>
					<td><em>string</em></td>
					<td>Postal code of an Address. When creating a Quote Addresses, sending a ZIP is optional but will yield more accurate Rates.</td>
				</tr>
				<tr>
					<td>state</td>
					<td>required for US purchase addresses</td>
					<td><em>string</em></td>
					<td>State values are only required for purchase Addresses in the United States. However, to receive more accurate quotes, passing it is generally recommended.</td>
				</tr>
				<tr>
					<td>country</td>
					<td>required for purchase<br>required for quote if no IP given</td>
					<td>ISO 3166-1-alpha-2 code (ISO 2 country code)</td>
					<td>Example: 'US' or 'DE'. All accepted values can be found on the <a href="http://www.iso.org/iso/country_codes/iso_3166_code_lists/country_names_and_code_elements.htm" target="_blank">Official ISO Website</a>. Sending a country is required for quote Addresses if an IP address is not included. If a quote Address only contains a country, the country's capital will be used as city value to determine general shipping costs to/within that country.</td>
				</tr>
				<tr>
					<td>phone</td>
					<td>optional</td>
					<td><em>string</em></td>
					<td>Purchase Addresses containing a phone number allow carriers to call the recipient when delivering the Parcel. This increases the probability of delivery and helps to avoid accessorial charges after a Parcel has been shipped.</td>
				</tr>
				<tr>
					<td>email</td>
					<td>required for purchase</td>
					<td><em>email</em></td>
					<td>E-mail address of the contact person. Must be in the format <em>"NAME@DOMAIN.TLD"</em>.</td>
				</tr>
				<tr>
					<td>IP</td>
					<td>required for quote if no country given</td>
					<td><em>IPv4 or IPv6</em></td>
					<td>Sending an IP address allows to generate quick and easy quotes for requests. Shippo will automatically find the closest street address for a given IP, usually with a preciseness of about 50 miles within the actual user location, given that no VPN is used.</td>
				</tr>
				<tr>
					<td>metadata</td>
					<td>optional</td>
					<td><em>string</em></td>
					<td>A string of up to 100 characters that can be filled with any additional information you want to attach to the object.</td>
				</tr>
			</tbody>
		</table>
	</div>

<h4>Response Schema</h4>
	<p><em>A response from the Address resource contains the request data, plus the data outlined below.</em></p>
	<div class="table-responsive">
		<table class="table table-bordered table-hover table-col-1-str">
			<thead class="italic">
				<tr>
					<td width="20%">Key</td>
					<td width="20%">Format / Values</td>
					<td>Description</td>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>object_state</td>
					<td>"COMPLETED"<br>"VALID"</td>
					<td>Completed Addresses are eligible for requesting quote Rates but lack at least one required value for purchasing Labels. In this case, the API has automatically completed the values with the best available approximation.<br><br>Valid addresses contain all required values and did not require any completion by the API. Only the latter can be used to purchase labels.</td>
				</tr>
				<tr>
					<td>object_purpose</td>
					<td>"QUOTE"<br>"PURCHASE"</td>
					<td>Indicates whether an Address can be used to purchase Labels or only to obtain Rate quotes.</td>
				</tr>
				<tr>
					<td>object_source</td>
					<td>"FULLY_ENTERED"<br>"ZIP_COUNTRY"<br>"CITY_COUNTRY"<br>"COUNTRY"<br>"IP"</td>
					<td>Addresses with an IP source were completely deducted from a given IP address.<br><br>
						ZIP-Country Addresses do not contain any approximated values that would usually change any carrier's Rates, but did not include all values required to purchase a Label.<br><br>
						Country Addresses contain a street as well as a ZIP/city combination that has been approximated based on the country given. In most cases, the city will be the country's capital.<br><br>
						City-Country Addresses do not contain any approximated values that would usually change any carrier's Rates, but did not include all values required to purchase a Label.<br><br>
						Fully entered Addresses only contain user-given values and are eligible for purchasing a Label.</td>
				</tr>
				<tr>
					<td>object_created</td>
					<td><em>datetime</em></td>
					<td>Date and time of Address creation.</td>
				</tr>
				<tr>
					<td>object_updated</td>
					<td><em>datetime</em></td>
					<td>Date and time of last Address update. Since you cannot update Addresses after they were created, this time stamp reflects the time when the Address was changed by Shippo's systems for the last time, e.g., during the approximation of one or more values.</td>
				</tr>
				<tr>
					<td>object_id</td>
					<td><em>string</em></td>
					<td>Unique identifier of the given Address object. This ID is required to create a Shipment object.</td>
				</tr>
				<tr>
					<td>object_owner</td>
					<td><em>string</em></td>
					<td>Username of the user who created the Address object.</td>
				</tr>
			</tbody>
		</table>
	</div>
{% endblock %}

docs/templates/apitesting.html
{% extends "docs.html" %}

{% block apicontent %}
<h2>Testing</h2>

<div class="alert alert-info">
	<i class="fa fa-info-circle pull-left"></i>
    In order to get rates and be able to print labels, you need to activate your desired carriers in your <a href="{% url 'user:usercarriers' %}">Account Carrier Settings</a>. This way, you always get the accurate rates for your account.
</div>

<h3>QUOTE and PURCHASE objects: Addresses and Shipments</h3>

<p>For <strong>Addresses</strong> and <strong>Shipments</strong>, the property <em>object_purpose</em> can be set to "QUOTE" or "PURCHASE". QUOTEable Addresses enjoy the benefit of automatic completion (e.g. by only sending a country or IP); Shipment Rates containing QUOTEable Addresses can not be purchased, however. Only PURCHASEable addresses (i.e. addresses containing only user-given data) can be used for Transactions.</p>

<p><strong>The <em>object_purpose</em> property (i.e. QUOTE or PURCHASE) does not determine the use of a carrier's test or production mode for a given Transaction.</strong></p>

<h3>TEST and PRODUCTION modes for Transactions</h3>

<p>Most of Shippo's carriers offer test servers for Transactions. Using test servers, you can conveniently test Transactions without having to pay for the label. Of course, you can not use the label for actual postage.</p>

<h4>How to set TEST or PRODUCTION for your Transactions</h4>
<p>Shippo allows you to set the test or production server on a <strong>per-carrier basis</strong>. You can enable or disable the use of a carrier's production server in your <a href="{% url 'user:usercarriers' %}">Shippo Carrier Settings</a>.</p>

{% endblock %}

docs/templates/billing.html
{% extends "docs.html" %}

{% block apicontent %}
<h2>Billing</h2>

<div class="alert alert-success">
    <strong>Our Promise: Shippo does not charge any fees for the use of the Shippo API while in beta.</strong><br>All fees listed below are charged by the corresponding carriers.
</div>

<h3>Shippo's No-Fee Promise</h3>

<p><strong>The use of the Shippo API beta is 100% free.</strong> When you purchase a postage label with Shippo, you only pay the shipping carrier directly for their services. All other API calls are free. We guarantee to not charge any setup, cancellation, monthly or storage fees. </p>

<h3>Additional Payment Charges</h3>

<p>In addition to the cost of a single label, some carriers do charge extra fees. Please transparently find all extra charges that you have to cover below:</p>

<h4>Additional USPS Charges</h4>
<p>USPS charges a commission of <strong>0.20$</strong> for each label generated through the API in addition to the rate price.

<h3>Shippo Pricing Help</h3>
<p>Shippo wants to make payments and pricing as easy as possible. We are already working on solutions to further improve your experience. If you have any questions, please do not hesitate to contact us at <a href="mailto:info@goshippo.com">info@goshippo.com</a>. We are happy to help!</p>

{% endblock %}

docs/templates/docs.html
{% extends "base.html" %}

{% block content %}

<div class="container page-inner">
	{% block apiheader %}{% endblock %}
	<div class="row margin-n-t-10">
		<div class="col-sm-3 col-xs-12 border-r-grey padding-l-sm padding-r-none padding-b-md">
			<div>
				<h4 class="padding-v-sm">Modules</h4>
				<ul class="list-noblt list-menu">
					<a href="{% url 'docs:overview' %}"><li {% if urlname == 'overview' %} class="active"{% endif %}>Overview</li></a>
					<a href="{% url 'docs:addresses' %}"><li {% if urlname == 'addresses' %} class="active"{% endif %}>Addresses</li></a>
					<a href="{% url 'docs:parcels' %}"><li {% if urlname == 'parcels' %} class="active"{% endif %}>Parcels</li></a>
					<a href="{% url 'docs:shipments' %}"><li {% if urlname == 'shipments' %} class="active"{% endif %}>Shipments</li></a>
					<a href="{% url 'docs:rates' %}"><li {% if urlname == 'rates' %} class="active"{% endif %}>Rates</li></a>
					<a href="{% url 'docs:transactions' %}"><li {% if urlname == 'transactions' %} class="active"{% endif %}>Transactions</li></a>
				</ul>
			</div>
			<div class="border-t-grey">
				<h4 class="padding-v-sm">Additional Information</h4>
				<ul class="list-noblt list-menu">
					<a href="{% url 'docs:testing' %}"><li {% if urlname == 'testing' %} class="active"{% endif %}>Testing</li></a>
				</ul>
			</div>
		</div>
		<div class="col-sm-9 col-xs-12 padding-l-md padding-bt-md">
			{% block apicontent %}{% endblock %}
		</div>
	</div>
</div>

{% endblock %}

docs/templates/labels.html
{% extends "docs.html" %}

{% block apicontent %}
<h2>Labels</h2>
<p>The labels module allows you to purchase any available shipping rate with one call.</p>
<div class="alert alert-warning alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong>The labels module currently is in the final review and test phase at Shippo. We aim to release this module beginning-mid of January.</strong>
</div>
{% endblock %}

docs/templates/overview.html
{% extends "docs.html" %}

{% block apiheader %}
	<div class="text-center">
		<h1 class="serif">API Documentation</h1>
		<p class="lead padding-b-md border-bottom">Get started now and automate your shipments within minutes. The API documentation gives you in-detail
			insights into the power of the Shippo API. Get started now!</p>
	</div>
{% endblock %}

{% block apicontent %}
<h2>Overview</h2>

<h4>API Resources</h4>
<p>All API URLs listed in this documentation are relative to <strong>https://api.goshippo.com/v1/</strong>. For example, the <a href="{% url 'docs:addresses' %}">/addresses/</a> resource is reachable at <strong>https://api.goshippo.com/v1/addresses/</strong>.</p>

<h4>SSL Prerequisite & Authentication</h4>
<p>The API is available via <strong>Secure Socket Layer (SSL) only</strong>. Insecure attempts to access the API will return HTTP status 403/Forbidden. The Shippo API requires <strong>Basic HTTP Authentication</strong> with your user name and password.</p>

<h4>Passing Request Data</h4>
<p>Request data is passed to the API by <strong>POSTing JSON arrays</strong> with the appropriate key/value-pairs to the respective resource. The documentation for each API resource contains more details on the values accepted by a given resource.</p>
<p>The returned data is also formatted as JSON array.</p>

<h4>Disposable Objects</h4>
<p>The Shippo API is built with simplicity in mind. While <strong>you can GET and POST Addresses, Parcels, Shipments and Transactions, you can only GET all other resources</strong>. This means that once you created an object, you cannot change it. Instead, create a new one with the desired values.</p>

<h4>Caveats</h4>
<p>While our technical team is working 24/7 to fix all issues, please help us improve the API by reporting any bugs, problems, questions or other issues to <a href="mailto:support@goshippo.com">support@goshippo.com</a>. Our support team will help you. Thanks in advance for your support!</p>

<h4>Browsable API</h4>
<p>In addition to this API, you may at anytime refer to the Browsable Shippo API  at <strong><a href="https://api.goshippo.com/v1/addresses/" target="_blank">https://api.goshippo.com/v1/addresses/</a></strong> to familiarize yourself with the structure and try out your first calls right in your browser.</p>

<h4>Questions? Problems?</h4>
<p>Have you run into difficulties or a resource just doesn't seem to work right? Let us know at <strong><a href="mailto:support@goshippo.com">support@goshippo.com</a></strong>. Our support team will help you.</p>

<h4>Shippo API Resources</h4>
<p><strong>Let's get started!</strong> Have a look at the following building blocks of the Shippo API and start to calculate Rates and print Labels in a few minutes!</p>
<ul>
	<li><a href="{% url 'docs:addresses' %}">Addresses</a></li>
	<li><a href="{% url 'docs:parcels' %}">Parcels</a></li>
	<li><a href="{% url 'docs:shipments' %}">Shipments</a></li>
	<li><a href="{% url 'docs:rates' %}">Rates</a></li>
	<li><a href="{% url 'docs:transactions' %}">Transactions</a></li>
</ul>

<h4>Shippo's Best Effort</h4>
<p>We are collecting and retrieving data from multiple data sources to be able to provide you with our unique service.<br />
<strong>While we are constantly improving and updating our data, due to the nature of our service, we are not able to guarantee the correctness or accuracy of the data provided. Under no circumstances will the operator of Shippo, Popout, Inc., be liable for incorrect, inaccurate or missing information (including, but not limited to incorrect pricing information or insurance values).</strong></p>

<h5>Warranty Disclaimer</h5>
<p>ANY DATA OR SERVICE IS PROVIDED TO THE REQUESTOR ON AN "AS IS, WHERE IS" BASIS, SOLELY UNDER THE USE AND DIRECTION OF THE REQUESTOR, WITHOUT WARRANTY OF ANY KIND (EITHER EXPRESS OR IMPLIED), INCLUDING BUT NOT LIMITED TO ANY IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A SPECIFIC OR GENERAL PURPOSE AND THOSE ARISING BY STATUTE OR BY LAW, OR FROM A CAUSE OF DEALING OR USAGE OF TRADE.</p>
<h5>Limitation of Liability</h5>
<p>IN NO EVENT, REGARDLESS OF CAUSE, SHALL POPOUT, INC. BE LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL, PUNITIVE OR CONSEQUENTIAL DAMAGES OF ANY KIND, WHETHER ARISING UNDER BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY OR OTHERWISE, AND WHETHER BASED ON THIS AGREEMENT OR OTHERWISE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
<h5>Restriction on Use of Service</h5>
<p>Our utmost goal is your satisfaction with our service. In order to ensure continuous operation and to prevent abuse, but not limited to these motives, we reserve the right at all times to remove any data on our service, to suspend or terminate users, and to reclaim usernames without liability to you. We also reserve the right to access, read, preserve, and disclose any information as we reasonably believe is necessary to (i) satisfy any applicable law, regulation, legal process or governmental request, (ii) enforce our terms, including investigation of potential violations hereof, (iii) detect, prevent, or otherwise address fraud, security or technical issues, (iv) respond to user support requests, or (v) protect the rights, property or safety of Popout, Inc., Shippo, its users and the public.</p>

{% endblock %}